// <auto-generated />
using System;
using DiscordDockerManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordDockerManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301000812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("DiscordDockerManager.Models.DockerContainerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerJoinPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerLeavePattern")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DockerContainerConfigs");
                });

            modelBuilder.Entity("DiscordDockerManager.Models.PlayerEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DockerContainerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawLogLine")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DockerContainerConfigId");

                    b.HasIndex("ContainerName", "Timestamp");

                    b.ToTable("PlayerEvents");
                });

            modelBuilder.Entity("DiscordDockerManager.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("DiscordDockerManager.Models.UserPermissionContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DockerContainerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserPermissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DockerContainerConfigId");

                    b.HasIndex("UserPermissionId", "DockerContainerConfigId")
                        .IsUnique();

                    b.ToTable("UserPermissionContainers");
                });

            modelBuilder.Entity("DiscordDockerManager.Models.PlayerEvent", b =>
                {
                    b.HasOne("DiscordDockerManager.Models.DockerContainerConfig", "DockerContainerConfig")
                        .WithMany("PlayerEvents")
                        .HasForeignKey("DockerContainerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DockerContainerConfig");
                });

            modelBuilder.Entity("DiscordDockerManager.Models.UserPermissionContainer", b =>
                {
                    b.HasOne("DiscordDockerManager.Models.DockerContainerConfig", "DockerContainerConfig")
                        .WithMany("UserPermissions")
                        .HasForeignKey("DockerContainerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordDockerManager.Models.UserPermission", "UserPermission")
                        .WithMany("ContainerPermissions")
                        .HasForeignKey("UserPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DockerContainerConfig");

                    b.Navigation("UserPermission");
                });

            modelBuilder.Entity("DiscordDockerManager.Models.DockerContainerConfig", b =>
                {
                    b.Navigation("PlayerEvents");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("DiscordDockerManager.Models.UserPermission", b =>
                {
                    b.Navigation("ContainerPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
